window.deputados = [
 {
  "id": 201916,
  "uri": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/deputados\/74090",
  "nome": "Átila Lins",
  "siglaPartido": "PP",
  "uriPartido": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/partidos\/37903",
  "siglaUf": "AM",
  "idLegislatura": 56,
  "urlFoto": "https:\/\/www.camara.leg.br\/internet\/deputado\/bandep\/74090.jpg",
  "email": "dep.atilalins@camara.leg.br",
  "DespesasTotal": "R$ 481.719,00",
  "nome_up": "ÁTILALINS"
 },
 {
  "id": 201914,
  "uri": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/deputados\/204551",
  "nome": "Bosco Saraiva",
  "siglaPartido": "SOLIDARIEDADE",
  "uriPartido": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/partidos\/37904",
  "siglaUf": "AM",
  "idLegislatura": 56,
  "urlFoto": "https:\/\/www.camara.leg.br\/internet\/deputado\/bandep\/204551.jpg",
  "email": "dep.boscosaraiva@camara.leg.br",
  "DespesasTotal": "R$ 459.934,74",
  "nome_up": "BOSCOSARAIVA"
 },
 {
  "id": 201915,
  "uri": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/deputados\/204572",
  "nome": "Capitão Alberto Neto",
  "siglaPartido": "REPUBLICANOS",
  "uriPartido": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/partidos\/37908",
  "siglaUf": "AM",
  "idLegislatura": 56,
  "urlFoto": "https:\/\/www.camara.leg.br\/internet\/deputado\/bandep\/204572.jpg",
  "email": "dep.capitaoalbertoneto@camara.leg.br",
  "DespesasTotal": "R$ 488.139,15",
  "nome_up": "CAPITÃOALBERTONETO"
 },
 {
  "id": 201917,
  "uri": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/deputados\/204569",
  "nome": "Delegado Pablo",
  "siglaPartido": "PSL",
  "uriPartido": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/partidos\/36837",
  "siglaUf": "AM",
  "idLegislatura": 56,
  "urlFoto": "https:\/\/www.camara.leg.br\/internet\/deputado\/bandep\/204569.jpg",
  "email": "dep.delegadopablo@camara.leg.br",
  "DespesasTotal": "R$ 387.397,76",
  "nome_up": "DELEGADOPABLO"
 },
 {
  "id": 201912,
  "uri": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/deputados\/204555",
  "nome": "José Ricardo",
  "siglaPartido": "PT",
  "uriPartido": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/partidos\/36844",
  "siglaUf": "AM",
  "idLegislatura": 56,
  "urlFoto": "https:\/\/www.camara.leg.br\/internet\/deputado\/bandep\/204555.jpg",
  "email": "dep.josericardo@camara.leg.br",
  "DespesasTotal": "R$ 479.271,32",
  "nome_up": "JOSÉRICARDO"
 },
 {
  "id": 201910,
  "uri": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/deputados\/204556",
  "nome": "Marcelo Ramos",
  "siglaPartido": "PL",
  "uriPartido": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/partidos\/37906",
  "siglaUf": "AM",
  "idLegislatura": 56,
  "urlFoto": "https:\/\/www.camara.leg.br\/internet\/deputado\/bandep\/204556.jpg",
  "email": "dep.marceloramos@camara.leg.br",
  "DespesasTotal": "R$ 479.242,42",
  "nome_up": "MARCELORAMOS"
 },
 {
  "id": 201913,
  "uri": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/deputados\/204557",
  "nome": "Sidney Leite",
  "siglaPartido": "PSD",
  "uriPartido": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/partidos\/36834",
  "siglaUf": "AM",
  "idLegislatura": 56,
  "urlFoto": "https:\/\/www.camara.leg.br\/internet\/deputado\/bandep\/204557.jpg",
  "email": "dep.sidneyleite@camara.leg.br",
  "DespesasTotal": "R$ 477.597,73",
  "nome_up": "SIDNEYLEITE"
 },
 {
  "id": 201911,
  "uri": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/deputados\/74356",
  "nome": "Silas Câmara",
  "siglaPartido": "REPUBLICANOS",
  "uriPartido": "https:\/\/dadosabertos.camara.leg.br\/api\/v2\/partidos\/37908",
  "siglaUf": "AM",
  "idLegislatura": 56,
  "urlFoto": "https:\/\/www.camara.leg.br\/internet\/deputado\/bandep\/74356.jpg",
  "email": "dep.silascamara@camara.leg.br",
  "DespesasTotal": "R$ 519.366,16",
  "nome_up": "SILASCÂMARA"
 }
]