window.deputados = [
  {
    "id": 201911,
    "nome": "ABDALA FRAXE",
    "foto": "ABDALA_FRAXE",
    "partido": "avante",
    "despesaTotal": 185411.50999999998,
    "nomeCivil": "Abdala Habib Fraxe Júnior",
    "naturalidade": "Boa Vista (RR)",
    "nascimento": "09\/19\/1969",
    "Email": "deputado.abdalafraxe@aleam.gov.br",
    "telefone": "(92) 3183-4434",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Abdala-1-200x300-1"
   },
   {
    "id": 201904,
    "nome": "ADJUTO AFONSO",
    "foto": "ADJUTO_AFONSO",
    "partido": "união brasil",
    "despesaTotal": 193267.74000000002,
    "nomeCivil": "Adjuto Rodrigues Afonso",
    "naturalidade": "Pauini (AM)",
    "nascimento": "16\/06",
    "Email": "deputado.adjutoafonso@aleam.gov.br",
    "telefone": "(92) 3183-4401",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Deputados-2019-afonso"
   },
   {
    "id": 201912,
    "nome": "ALESSANDRA CAMPÊLO",
    "foto": "ALESSANDRA_CAMPÊLO",
    "partido": "partido social cristão",
    "despesaTotal": 178215.21000000002,
    "nomeCivil": "Alessandra Campêlo da Silva",
    "naturalidade": "Manaus (AM)",
    "nascimento": "11\/01\/1974",
    "Email": "deputada.alessandracampelo@aleam.gov.br",
    "telefone": "(92) 3183-4375",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2022\/04\/Deputados-2023-ALESSANDRA-683x1024"
   },
   {
    "id": 201914,
    "nome": "CABO MACIEL",
    "foto": "CABO_MACIEL",
    "partido": "partido liberal",
    "despesaTotal": 178642.45,
    "nomeCivil": "Alcimar Maciel Pereira",
    "naturalidade": "Humaitá (AM)",
    "nascimento": "06\/07\/1972",
    "Email": "deputado.cabomaciel@aleam.gov.br",
    "telefone": "(92) 3183-4403",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Cabo-Maciel-200x300-1"
   },
   {
    "id": 201902,
    "nome": "CARLINHOS BESSA",
    "foto": "CARLINHOS_BESSA",
    "partido": "partido verde",
    "despesaTotal": 162191.59999999998,
    "nomeCivil": "Carlos Eduardo Bessa de Sá",
    "naturalidade": "Tefé (AM)",
    "nascimento": "05\/22\/1984",
    "Email": "deputado.carlinhosbessa@aleam.gov.br",
    "telefone": "(92) 3183-4436",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/dep-cb-200x300-1.jpg"
   },
   {
    "id": 201905,
    "nome": "DELEGADO PÉRICLES",
    "foto": "DELEGADO_PÉRICLES",
    "partido": "partido liberal",
    "despesaTotal": 135431.09,
    "nomeCivil": "Péricles Rodrigues do Nascimento",
    "naturalidade": "Manaus (AM)",
    "nascimento": "08\/27\/1977",
    "Email": "deputado.delegadopericles@aleam.gov.br",
    "telefone": "(92) 3183-4427",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/IMG_9078-2-200x300-1"
   },
   {
    "id": 201916,
    "nome": "DR. GOMES",
    "foto": "DR_GOMES",
    "partido": "partido social cristão",
    "despesaTotal": 183804.16999999998,
    "nomeCivil": "Francisco do Nascimento Gomes",
    "naturalidade": "Cruzeiro do Sul (AC)",
    "nascimento": "09\/08\/1974",
    "Email": "deputado.drgomes@aleam.gov.br",
    "telefone": "(92) 3183-4406",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Dr.-Gome-200x300-200x300-1"
   },
   {
    "id": 201903,
    "nome": "DRA. MAYARA",
    "foto": "DRA_MAYARA",
    "partido": "republicanos",
    "despesaTotal": 175529.54,
    "nomeCivil": "Mayara Monique Figueiredo Pinheiro Reis",
    "naturalidade": "Manaus (AM)",
    "nascimento": "13\/04",
    "Email": "deputada.mayarapinheiro@aleam.gov.br",
    "telefone": "(92) 3183-4412",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Deputados-Mayara-2020-1-200x300-1"
   },
   {
    "id": 201910,
    "nome": "FELIPE SOUZA",
    "foto": "FELIPE_SOUZA",
    "partido": "patriota",
    "despesaTotal": 184008,
    "nomeCivil": "Luis Felipe Silva de Souza",
    "naturalidade": "Manaus (AM)",
    "nascimento": "10\/04\/1971",
    "Email": "deputado.felipesouza@aleam.gov.br",
    "telefone": "(92) 3183-4421",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Felipe-Souza-1-200x300-1"
   },
   {
    "id": 201917,
    "nome": "JOANA DARC",
    "foto": "JOANA_DARC",
    "partido": "união brasil",
    "despesaTotal": 156491.22,
    "nomeCivil": "Joana Darc dos Santos Cordeiros",
    "naturalidade": "Manaus (AM)",
    "nascimento": "03\/08",
    "Email": "deputada.joanadarc@aleam.gov.br",
    "telefone": "(92) 3183-4383",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Joana-Darc-683x1024"
   },
   {
    "id": 201918,
    "nome": "JOÃO LUIZ",
    "foto": "JOÃO_LUIZ",
    "partido": "republicanos",
    "despesaTotal": 143126.05,
    "nomeCivil": "João Luiz Almeida da Silva",
    "naturalidade": "Rio de Janeiro (RJ)",
    "nascimento": "29\/06",
    "Email": "deputado.joaoluiz@aleam.gov.br",
    "telefone": "(92) 3183-4909",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Joao-Luiz-1-200x300-1"
   },
   {
    "id": 201901,
    "nome": "ROBERTO CIDADE",
    "foto": "ROBERTO_CIDADE",
    "partido": "união brasil",
    "despesaTotal": 169148.48,
    "nomeCivil": "Roberto Maia Cidade Filho",
    "naturalidade": "Manaus (AM)",
    "nascimento": "10\/02\/1986",
    "Email": "deputado.robertocidade@aleam.gov.br",
    "telefone": "(92) 3183-4391",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Dep_RC_-200x300-1"
   },
   {
    "id": 201907,
    "nome": "SINÉSIO CAMPOS",
    "foto": "SINÉSIO_CAMPOS",
    "partido": "partido dos trabalhadores",
    "despesaTotal": 192665.18,
    "nomeCivil": "Sinésio da Silva Campos",
    "naturalidade": "Santarém (PA)",
    "nascimento": "03\/12",
    "Email": "deputado.sinesio@aleam.gov.br",
    "telefone": "(92) 3183-4432",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Deputados-2021-Sinesio-sem-fundo-683x1024"
   },
   {
    "id": 201924,
    "nome": "WILKER BARRETO",
    "foto": "WILKER_BARRETO",
    "partido": "cidadania23",
    "despesaTotal": 188800,
    "nomeCivil": "Mauricio Wilker de Azevedo Barreto",
    "naturalidade": "Manaus (AM)",
    "nascimento": "08\/01\/1976",
    "Email": "deputado.wilkerbarreto@aleam.gov.br",
    "telefone": "(92) 3183-4388",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2021\/05\/Dep_WBarreto"
   },
   {
    "id": 201925,
    "nome": "COMANDANTE DAN",
    "foto": "COMANDANTE_DAN",
    "partido": "partido social cristão",
    "despesaTotal": 142635,
    "nomeCivil": "Dan Câmara",
    "naturalidade": "Rio Branco (AC)",
    "nascimento": "24\/08",
    "Email": "deputado.comandantedan@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Comandante-Dan"
   },
   {
    "id": 201926,
    "nome": "CRISTIANO D’ANGELO",
    "foto": "CRISTIANO_DANGELO",
    "partido": "movimento democrático brasileiro",
    "despesaTotal": 124722.4,
    "nomeCivil": "Cristiano da Silva D'Angelo",
    "naturalidade": "Manacapuru (AM)",
    "nascimento": "22\/09",
    "Email": "deputado.cristianodangelo@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Cristiano-DAngelo"
   },
   {
    "id": 201927,
    "nome": "DANIEL ALMEIDA",
    "foto": "DANIEL_ALMEIDA",
    "partido": "avante",
    "despesaTotal": 115769.07,
    "nomeCivil": "Daniel Djuda Pereira de Almeida",
    "naturalidade": "Manaus (AM)",
    "nascimento": "11\/08",
    "Email": "deputado.danielalmeida@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/02\/Daniel-Almeida"
   },
   {
    "id": 201928,
    "nome": "DÉBORA MENEZES",
    "foto": "DEBORA_MENEZES",
    "partido": "partido liberal",
    "despesaTotal": 136300,
    "nomeCivil": "Débora Salgueiro de Menezes",
    "naturalidade": "Taubaté (SP)",
    "nascimento": "07\/11\/1994",
    "Email": "deputada.deboramenezes@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Debora-Menezes"
   },
   {
    "id": 201929,
    "nome": "DR. GEORGE LINS",
    "foto": "DR_GEORGE_LINS",
    "partido": "união brasil",
    "despesaTotal": 149386.85,
    "nomeCivil": "George Augusto Monteiro Lins de Albuquerque",
    "naturalidade": "Manaus (AM)",
    "nascimento": "23\/12",
    "Email": "deputado.drgeorgelins@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Dr-George-Lins"
   },
   {
    "id": 201930,
    "nome": "MÁRIO CÉSAR FILHO",
    "foto": "MARIO_CESAR_FILHO",
    "partido": "união brasil",
    "despesaTotal": 149455.87,
    "nomeCivil": "Mário César Rodrigues Balduino",
    "naturalidade": "Parnamirim (RN)",
    "nascimento": "29\/02",
    "Email": "deputado.mariocesarfilho@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Mario-Cesar-Filho"
   },
   {
    "id": 201931,
    "nome": "MAYRA DIAS",
    "foto": "MAYRA_DIAS",
    "partido": "avante",
    "despesaTotal": 149548.95,
    "nomeCivil": "Mayra Benita Alves Dias Garcia",
    "naturalidade": "Itacoatiara (AM)",
    "nascimento": "28\/09",
    "Email": "deputada.mayradias@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Mayra-Dias"
   },
   {
    "id": 201932,
    "nome": "ROZENHA",
    "foto": "ROZENHA",
    "partido": "partido da mulher brasileira",
    "despesaTotal": 149500,
    "nomeCivil": "Ednailson Leite Rozenha",
    "naturalidade": "Porto Velho (RO)",
    "nascimento": "15\/02",
    "Email": "deputado.rozenha@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Rozenha"
   },
   {
    "id": 201933,
    "nome": "THIAGO ABRAHIM",
    "foto": "THIAGO_ABRAHIM",
    "partido": "união brasil",
    "despesaTotal": 10392,
    "nomeCivil": "Jorge Thiago Carvalho Abrahim",
    "naturalidade": "Manaus (AM)",
    "nascimento": "06\/12",
    "Email": "deputado.thiagoabrahim@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Thiago-Abrahim"
   },
   {
    "id": 201934,
    "nome": "WANDERLEY MONTEIRO",
    "foto": "WANDERLEY_MONTEIRO",
    "partido": "avante",
    "despesaTotal": 144740,
    "nomeCivil": "Wanderley Caldeira Monteiro",
    "naturalidade": "Manaus (AM)",
    "nascimento": "14\/10",
    "Email": "deputado.wanderleymonteiro@aleam.gov.br",
    "telefone": "Nan",
    "urlfoto": "https:\/\/www.aleam.gov.br\/wp-content\/uploads\/2023\/01\/Wanderley-Monteiro"
   }
]